/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author User
 */
public class InterfaceJuego extends javax.swing.JFrame {
    private JButton[][] casillerosBotones=new JButton[8][8];
    private Ficha[][] casillerosFichas=new Ficha[8][8];
    private ArrayList<JButton> movimiento=new ArrayList<JButton>();
    private ArrayList<String> posicionesPosibles= new ArrayList<String>();
    private Rey[] reyes=new Rey[2];
    private int turnoJugador=1;
    private String colorTurnoJugador="blanco";
    private FondoPanel fondo=new FondoPanel("/imagenes/fondo1.jpg");
    private boolean reemplazarPeon=false;
    private int XultimoMovido;
    private int YultimoMovido;
    private boolean jake=false;        
    private ArrayList<String> casillerosAtacados=new ArrayList<String>();
    
    public InterfaceJuego() {
        this.setContentPane(fondo);
        initComponents();
        llenarCasillerosBotones();
        darCoordenadasBotones();
        ponerFichasEnTableroFichas();
        ponerFichasEnBotones();
        btnVolverAJugar.setVisible(false);
        escogerFicha.setVisible(false);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        H1 = new javax.swing.JButton();
        H5 = new javax.swing.JButton();
        H6 = new javax.swing.JButton();
        H7 = new javax.swing.JButton();
        H8 = new javax.swing.JButton();
        H4 = new javax.swing.JButton();
        G5 = new javax.swing.JButton();
        G6 = new javax.swing.JButton();
        H2 = new javax.swing.JButton();
        H3 = new javax.swing.JButton();
        G7 = new javax.swing.JButton();
        G8 = new javax.swing.JButton();
        G4 = new javax.swing.JButton();
        G2 = new javax.swing.JButton();
        G3 = new javax.swing.JButton();
        G1 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        F8 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        E6 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        E7 = new javax.swing.JButton();
        E8 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        D8 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        A1 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        escogerFicha = new javax.swing.JPanel();
        opciones = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnVolverAJugar = new javax.swing.JButton();
        jaketxt1 = new javax.swing.JLabel();
        ganadortxt = new javax.swing.JLabel();
        player1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new FondoPanel("/imagenes/persona.png");
        player2 = new javax.swing.JPanel();
        jPanel8 = new FondoPanel("/imagenes/persona.png");
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1180, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(146, 81, 37));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 200, 108));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        H1.setBackground(new java.awt.Color(255, 200, 108));
        H1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H1MouseClicked(evt);
            }
        });
        H1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H1ActionPerformed(evt);
            }
        });

        H5.setBackground(new java.awt.Color(255, 200, 108));
        H5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H5MouseClicked(evt);
            }
        });

        H6.setBackground(new java.awt.Color(146, 81, 37));
        H6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H6MouseClicked(evt);
            }
        });

        H7.setBackground(new java.awt.Color(255, 200, 108));
        H7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H7MouseClicked(evt);
            }
        });
        H7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H7ActionPerformed(evt);
            }
        });

        H8.setBackground(new java.awt.Color(146, 81, 37));
        H8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H8MouseClicked(evt);
            }
        });

        H4.setBackground(new java.awt.Color(146, 81, 37));
        H4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H4MouseClicked(evt);
            }
        });

        G5.setBackground(new java.awt.Color(146, 81, 37));
        G5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G5MouseClicked(evt);
            }
        });

        G6.setBackground(new java.awt.Color(255, 200, 108));
        G6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G6MouseClicked(evt);
            }
        });

        H2.setBackground(new java.awt.Color(146, 81, 37));
        H2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H2MouseClicked(evt);
            }
        });
        H2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H2ActionPerformed(evt);
            }
        });

        H3.setBackground(new java.awt.Color(255, 200, 108));
        H3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H3MouseClicked(evt);
            }
        });

        G7.setBackground(new java.awt.Color(146, 81, 37));
        G7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G7MouseClicked(evt);
            }
        });

        G8.setBackground(new java.awt.Color(255, 200, 108));
        G8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G8MouseClicked(evt);
            }
        });

        G4.setBackground(new java.awt.Color(255, 200, 108));
        G4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G4MouseClicked(evt);
            }
        });

        G2.setBackground(new java.awt.Color(255, 200, 108));
        G2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G2MouseClicked(evt);
            }
        });
        G2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G2ActionPerformed(evt);
            }
        });

        G3.setBackground(new java.awt.Color(146, 81, 37));
        G3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G3MouseClicked(evt);
            }
        });
        G3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G3ActionPerformed(evt);
            }
        });

        G1.setBackground(new java.awt.Color(146, 81, 37));
        G1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G1MouseClicked(evt);
            }
        });
        G1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G1ActionPerformed(evt);
            }
        });

        E1.setBackground(new java.awt.Color(146, 81, 37));
        E1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E1MouseClicked(evt);
            }
        });
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });

        F1.setBackground(new java.awt.Color(255, 200, 108));
        F1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F1MouseClicked(evt);
            }
        });
        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ActionPerformed(evt);
            }
        });

        F5.setBackground(new java.awt.Color(255, 200, 108));
        F5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });

        F6.setBackground(new java.awt.Color(146, 81, 37));
        F6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F6MouseClicked(evt);
            }
        });

        F7.setBackground(new java.awt.Color(255, 200, 108));
        F7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F7MouseClicked(evt);
            }
        });

        F8.setBackground(new java.awt.Color(146, 81, 37));
        F8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F8MouseClicked(evt);
            }
        });

        F4.setBackground(new java.awt.Color(146, 81, 37));
        F4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F4MouseClicked(evt);
            }
        });

        E5.setBackground(new java.awt.Color(146, 81, 37));
        E5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E5MouseClicked(evt);
            }
        });

        E6.setBackground(new java.awt.Color(255, 200, 108));
        E6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E6MouseClicked(evt);
            }
        });

        F2.setBackground(new java.awt.Color(146, 81, 37));
        F2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F2MouseClicked(evt);
            }
        });
        F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F2ActionPerformed(evt);
            }
        });

        F3.setBackground(new java.awt.Color(255, 200, 108));
        F3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F3MouseClicked(evt);
            }
        });

        E7.setBackground(new java.awt.Color(146, 81, 37));
        E7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E7MouseClicked(evt);
            }
        });

        E8.setBackground(new java.awt.Color(255, 200, 108));
        E8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E8MouseClicked(evt);
            }
        });
        E8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                E8KeyReleased(evt);
            }
        });

        E4.setBackground(new java.awt.Color(255, 200, 108));
        E4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E4MouseClicked(evt);
            }
        });

        E2.setBackground(new java.awt.Color(255, 200, 108));
        E2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2MouseClicked(evt);
            }
        });
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2ActionPerformed(evt);
            }
        });

        E3.setBackground(new java.awt.Color(146, 81, 37));
        E3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E3MouseClicked(evt);
            }
        });

        D3.setBackground(new java.awt.Color(255, 200, 108));
        D3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D3MouseClicked(evt);
            }
        });

        D8.setBackground(new java.awt.Color(146, 81, 37));
        D8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D8MouseClicked(evt);
            }
        });

        D6.setBackground(new java.awt.Color(146, 81, 37));
        D6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D6MouseClicked(evt);
            }
        });

        C4.setBackground(new java.awt.Color(255, 200, 108));
        C4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C4MouseClicked(evt);
            }
        });

        C3.setBackground(new java.awt.Color(146, 81, 37));
        C3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C3MouseClicked(evt);
            }
        });

        D4.setBackground(new java.awt.Color(146, 81, 37));
        D4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D4MouseClicked(evt);
            }
        });

        C6.setBackground(new java.awt.Color(255, 200, 108));
        C6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C6MouseClicked(evt);
            }
        });

        C7.setBackground(new java.awt.Color(146, 81, 37));
        C7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C7MouseClicked(evt);
            }
        });

        C8.setBackground(new java.awt.Color(255, 200, 108));
        C8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C8MouseClicked(evt);
            }
        });

        D2.setBackground(new java.awt.Color(146, 81, 37));
        D2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D2MouseClicked(evt);
            }
        });
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });

        C2.setBackground(new java.awt.Color(255, 200, 108));
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C2MouseClicked(evt);
            }
        });
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });

        C5.setBackground(new java.awt.Color(146, 81, 37));
        C5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C5MouseClicked(evt);
            }
        });

        D7.setBackground(new java.awt.Color(255, 200, 108));
        D7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D7MouseClicked(evt);
            }
        });

        D5.setBackground(new java.awt.Color(255, 200, 108));
        D5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D5MouseClicked(evt);
            }
        });

        D1.setBackground(new java.awt.Color(255, 200, 108));
        D1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D1MouseClicked(evt);
            }
        });
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });

        C1.setBackground(new java.awt.Color(146, 81, 37));
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C1MouseClicked(evt);
            }
        });
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });

        A1.setBackground(new java.awt.Color(146, 81, 37));
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });

        B1.setBackground(new java.awt.Color(255, 200, 108));
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(255, 200, 108));
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });

        B6.setBackground(new java.awt.Color(146, 81, 37));
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
        });

        B7.setBackground(new java.awt.Color(255, 200, 108));
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7MouseClicked(evt);
            }
        });

        B8.setBackground(new java.awt.Color(146, 81, 37));
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B8MouseClicked(evt);
            }
        });

        B4.setBackground(new java.awt.Color(146, 81, 37));
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });

        A5.setBackground(new java.awt.Color(146, 81, 37));
        A5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A5MouseClicked(evt);
            }
        });

        A6.setBackground(new java.awt.Color(255, 200, 108));
        A6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A6MouseClicked(evt);
            }
        });

        B2.setBackground(new java.awt.Color(146, 81, 37));
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(255, 200, 108));
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });

        A7.setBackground(new java.awt.Color(146, 81, 37));
        A7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A7MouseClicked(evt);
            }
        });

        A8.setBackground(new java.awt.Color(255, 200, 108));
        A8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A8MouseClicked(evt);
            }
        });

        A4.setBackground(new java.awt.Color(255, 200, 108));
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A4MouseClicked(evt);
            }
        });

        A2.setBackground(new java.awt.Color(255, 200, 108));
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2MouseClicked(evt);
            }
        });
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });

        A3.setBackground(new java.awt.Color(146, 81, 37));
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(H1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(H2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(H3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(H4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(H5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(H6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(H7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(H8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(G2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(G3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(G4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(G6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(G7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(G8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(F5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(F6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(F7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(F8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(E5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(E6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(E7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(E8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(H7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(H1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(H8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 32, 540, 540));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 620, 605));

        escogerFicha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reina", "Caballo", "Torre", "Alfil" }));
        opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesActionPerformed(evt);
            }
        });
        escogerFicha.add(opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 35, -1, -1));

        jButton1.setText("Confirmar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        escogerFicha.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setText("Seleccionar Ficha");
        escogerFicha.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        getContentPane().add(escogerFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 130, 140, 120));

        btnVolverAJugar.setBackground(new java.awt.Color(123, 123, 123));
        btnVolverAJugar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnVolverAJugar.setForeground(new java.awt.Color(225, 225, 225));
        btnVolverAJugar.setText("Volver a jugar");
        btnVolverAJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverAJugarMouseClicked(evt);
            }
        });
        btnVolverAJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverAJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 680, -1, 40));

        jaketxt1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jaketxt1.setForeground(new java.awt.Color(11, 19, 125));
        getContentPane().add(jaketxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, 78, 26));

        ganadortxt.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        ganadortxt.setForeground(new java.awt.Color(11, 19, 125));
        getContentPane().add(ganadortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 450, 78, 26));

        player1.setBackground(new java.awt.Color(0, 179, 0));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel1.setText("PLAYER1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout player1Layout = new javax.swing.GroupLayout(player1);
        player1.setLayout(player1Layout);
        player1Layout.setHorizontalGroup(
            player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        player1Layout.setVerticalGroup(
            player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 210, 180));

        player2.setBackground(new java.awt.Color(123, 123, 123));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel2.setText("PLAYER2");

        javax.swing.GroupLayout player2Layout = new javax.swing.GroupLayout(player2);
        player2.setLayout(player2Layout);
        player2Layout.setHorizontalGroup(
            player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        player2Layout.setVerticalGroup(
            player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 210, 180));

        pack();
    }// </editor-fold>                        

    private void H1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void H2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void G2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void G1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void F2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(B1);    
    }                               

    private void C1MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(C1); 
    }                               

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(B3);
    }                               

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(B4);
    }                               

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(B5);
    }                               

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(B6);
    }                               

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(B2);
    }                               

    private void B7MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(B7);
    }                               

    private void B8MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(B8);
    }                               

    private void C2MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(C2);
    }                               

    private void C3MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(C3);
    }                               

    private void C4MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(C4);
    }                               

    private void C5MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(C5);
    }                               

    private void C6MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(C6);
    }                               

    private void C7MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(C7);
    }                               

    private void C8MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(C8);
    }                               

    private void D1MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(D1);
    }                               

    private void D2MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(D2);
    }                               

    private void D3MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(D3);
    }                               

    private void D4MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(D4);
    }                               

    private void D5MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(D5);
    }                               

    private void D6MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(D6);
    }                               

    private void D7MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(D7);
    }                               

    private void D8MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(D8);
    }                               

    private void E1MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(E1);
    }                               

    private void E2MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(E2);
    }                               

    private void E3MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(E3);
    }                               

    private void E4MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(E4);
    }                               

    private void E5MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(E5);
    }                               

    private void E6MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(E6);
    }                               

    private void E7MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(E7);
    }                               

    private void E8KeyReleased(java.awt.event.KeyEvent evt) {                               
        // TODO add your handling code here:
    }                              

    private void E8MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(E8);
    }                               

    private void F1MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(F1);
    }                               

    private void F2MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(F2);
    }                               

    private void F3MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(F3);
    }                               

    private void F4MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(F4);
    }                               

    private void F5MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(F5);
    }                               

    private void F6MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(F6);
    }                               

    private void F7MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(F7);
    }                               

    private void F8MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(F8);
    }                               

    private void G1MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(G1);
    }                               

    private void G2MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(G2);
    }                               

    private void G3MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(G3);
    }                               

    private void G4MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(G4);
    }                               

    private void G5MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(G5);
    }                               

    private void G6MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(G6);
    }                               

    private void G7MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(G7);
    }                               

    private void G8MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(G8);
    }                               

    private void H1MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(H1);
    }                               

    private void H2MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(H2);
    }                               

    private void H3MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(H3);
    }                               

    private void H4MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(H4);
    }                               

    private void H5MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(H5);
    }                               

    private void H6MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(H6);
    }                               

    private void H7MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(H7);
    }                               

    private void H8MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(H8);
    }                               

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(A1);
    }                               

    private void A2MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(A2);
    }                               

    private void A3MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(A3);
    }                               

    private void A4MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(A4);
    }                               

    private void A5MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(A5);
    }                               

    private void A6MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(A6);
    }                               

    private void A7MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(A7);
    }                               

    private void A8MouseClicked(java.awt.event.MouseEvent evt) {                                
        casilleroClickeado(A8);
    }                               

    private void btnVolverAJugarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void btnVolverAJugarMouseClicked(java.awt.event.MouseEvent evt) {                                             
        turnoJugador=1;
        colorTurnoJugador="blanco";
        ganadortxt.setText("");
        vaciarTableroBotones();
        vaciarTableroFichas();
        ponerFichasEnTableroFichas();
        ponerFichasEnBotones();
        btnVolverAJugar.setVisible(false);
    }                                            

    private void opcionesActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        String opcion=(String) opciones.getSelectedItem();
        opcion=opcion.toLowerCase();
        String color=casillerosFichas[YultimoMovido][XultimoMovido].getColor();
        JButton boton=casillerosBotones[YultimoMovido][XultimoMovido];
        
        casillerosFichas[YultimoMovido][XultimoMovido]=null;
         
        if(opcion.equals("reina")){
            casillerosFichas[YultimoMovido][XultimoMovido]=new Reina(color,"/imagenes/"+opcion+"-"+color+".png",boton);
        }else if(opcion.equals("caballo")){
            casillerosFichas[YultimoMovido][XultimoMovido]=new Caballo(color,"/imagenes/"+opcion+"-"+color+".png",boton);
        }else if(opcion.equals("torre")){
            casillerosFichas[YultimoMovido][XultimoMovido]=new Torre(color,"/imagenes/"+opcion+"-"+color+".png",boton);
        }else{
            casillerosFichas[YultimoMovido][XultimoMovido]=new Alfil(color,"/imagenes/"+opcion+"-"+color+".png",boton);
        }
        
        casillerosFichas[YultimoMovido][XultimoMovido].setMovimientosRealizados(1);
        colocarPieza(casillerosFichas[YultimoMovido][XultimoMovido]);
        
        reemplazarPeon=false;
        escogerFicha.setVisible(false);
    }                                     

    private void H7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void G3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void vaciarTableroBotones(){
        
        for(int i=0;i<casillerosBotones.length;i++){
            for(int j=0;j<casillerosBotones[0].length;j++){
                casillerosBotones[i][j].setIcon(null);
            }
        }
    }
    private void vaciarTableroFichas(){
        for(int i=0;i<casillerosFichas.length;i++){
            for(int j=0;j<casillerosFichas[0].length;j++){
                casillerosFichas[i][j]=null;
            }
        }
    }

    public void pintarMovimientosPosibles(){
        
        int y,x;

        for(int i=0;i<posicionesPosibles.size();i++){
            String indices[] = posicionesPosibles.get(i).split(" ");
            y=Integer.parseInt(indices[0]);
            x=Integer.parseInt(indices[1]);

            casillerosBotones[y][x].setBackground(Color.BLACK);
        }
    
    }
    public boolean comprobarMovimientoValido(int y,int x){
        
        String movimiento=y+" "+x;
        for(int i=0;i<posicionesPosibles.size();i++){
            
            if(posicionesPosibles.get(i).equals(movimiento))
                return true;
        }
        return false;    
    
    }
    public void pintarBackgroundTablero(){
    
        int contadorLineal=1;

        for(int i=0;i<casillerosBotones.length;i++){
            for(int j=0;j<casillerosBotones[0].length;j++){
                
                if(contadorLineal%2==1){
                    casillerosBotones[i][j].setBackground(new Color(255,200,108));
                }else{
                    casillerosBotones[i][j].setBackground(new Color(146,81,37));
                }
                if(j%8==7){
                   contadorLineal++; 
                }
                contadorLineal++;
            }
        }
    
    }
    
    private void moverPieza(){
        int xanterior=(int)(movimiento.get(0).getAlignmentX()*10);
        int yanterior=(int)(movimiento.get(0).getAlignmentY()*10);
        int xnuevo=(int)(movimiento.get(1).getAlignmentX()*10);
        int ynuevo=(int)(movimiento.get(1).getAlignmentY()*10);
              
        //enroque se mueve la torre tambien
        if(casillerosFichas[yanterior][xanterior] instanceof Rey){
            if(xanterior-xnuevo==2){
                atributosMover(yanterior,3,yanterior,0);
            }else if(xnuevo-xanterior==2){
                atributosMover(yanterior,5,yanterior,7);
            }   
        }

        //movimiento especial peon
        if(casillerosFichas[yanterior][xanterior] instanceof Peon){
            if(xanterior!=xnuevo && yanterior!=ynuevo && casillerosFichas[ynuevo][xnuevo]==null){
                eliminarFicha(yanterior,xnuevo);
                System.out.println("movimiento especial peon");
            }   
        }
        atributosMover(ynuevo,xnuevo,yanterior,xanterior);

    }
    private void eliminarFicha(int Y,int X){
        casillerosFichas[Y][X]=null;
        casillerosBotones[Y][X].setIcon(null);
    }
    private void atributosMover(int ynuevo,int xnuevo,int yanterior,int xanterior){
        Ficha estaFicha=casillerosFichas[yanterior][xanterior];
        int movimientosPieza=estaFicha.getMovimientosRealizados();
        
        //atributos
        estaFicha.setMovimientosRealizados(movimientosPieza+1);
        estaFicha.setPosX(xnuevo);
        estaFicha.setPosY(ynuevo);
        estaFicha.setBoton(casillerosBotones[ynuevo][xnuevo]);
        
        //imagenBoton    
        casillerosBotones[ynuevo][xnuevo].setIcon(casillerosBotones[yanterior][xanterior].getIcon());   
        casillerosBotones[yanterior][xanterior].setIcon(null);
        
        
        //matamos ala ficha comida
        if(casillerosFichas[ynuevo][xnuevo]!=null){
            casillerosFichas[ynuevo][xnuevo].setVive(false);
        }
        
        //mover casillero de ficha
        casillerosFichas[ynuevo][xnuevo]=estaFicha;
        casillerosFichas[yanterior][xanterior]=null;
        
    }
    
    private void casilleroClickeado(JButton bt){
        int y,x;
        String colorAtacado;
        
        x=(int)(bt.getAlignmentX()*10);
        y=(int)(bt.getAlignmentY()*10);
        Ficha fichaClickeada=casillerosFichas[y][x];
 
        if (movimiento.size() < 1 && fichaClickeada != null && fichaClickeada.getColor().equals(colorTurnoJugador) && comprobarVidaReyes() && reemplazarPeon==false) {

            fichaClickeada.getBoton().setBackground(Color.BLACK);
            fichaClickeada.movimientosPosibles(posicionesPosibles, casillerosFichas,YultimoMovido,XultimoMovido);
            pintarMovimientosPosibles();
            movimiento.add(bt);
            
        }else if (movimiento.size() == 1 && comprobarVidaReyes() && reemplazarPeon==false) {
            movimiento.add(bt);
            
            
            if (comprobarMovimientoValido(y, x) && !comprobarSiHayJakeDespuesDeMover(y,x,colorTurnoJugador)) {
                moverPieza();
                
                cambiarTurnoJugador();
                XultimoMovido=x;
                YultimoMovido=y;    
                posicionesPosibles.clear();
                //comprobar jake despues de mover
                fichaClickeada=casillerosFichas[y][x];
                fichaClickeada.movimientosPosibles(posicionesPosibles, casillerosFichas,YultimoMovido,XultimoMovido);
                //
            }
            System.out.println("y es : "+y);
            if(casillerosFichas[y][x] instanceof Peon){
                if(y==0 || y==7){
                    escogerFicha.setVisible(true);    
                    reemplazarPeon=true;
                }
            }
            if(comprobarsiHayJake("blanco") || comprobarsiHayJake("negro")){
                ganadortxt.setText("JAKE");
                jake=true;
            }else{
                ganadortxt.setText("");
                jake=false;
            }
            movimiento.clear();
            posicionesPosibles.clear();
            pintarBackgroundTablero();
            casillerosAtacados.clear();
        }
        if(!comprobarVidaReyes()){
                mostrarGanador();
                btnVolverAJugar.setVisible(true);
        }
    }  
    public boolean comprobarSiHayJakeDespuesDeMover(int y,int x,String colorAtacado){
        int xanterior=(int)(movimiento.get(0).getAlignmentX()*10);
        int yanterior=(int)(movimiento.get(0).getAlignmentY()*10);
        boolean valor;
        Ficha fichaMoviendo=casillerosFichas[yanterior][xanterior];
        Ficha fichaComida;
        
        if(fichaMoviendo instanceof Rey){
            fichaMoviendo.setPosX(x);
            fichaMoviendo.setPosY(y);
        }
        casillerosFichas[yanterior][xanterior]=null;
        
        if(casillerosFichas[y][x]==null){
            casillerosFichas[y][x]=fichaMoviendo;
            valor=comprobarsiHayJake(colorAtacado); 
            casillerosFichas[y][x]=null;
        }else{
            fichaComida=casillerosFichas[y][x];
            casillerosFichas[y][x]=fichaMoviendo;
            valor=comprobarsiHayJake(colorAtacado); 
            casillerosFichas[y][x]=fichaComida;
        }
        
        if(fichaMoviendo instanceof Rey){
            fichaMoviendo.setPosX(xanterior);
            fichaMoviendo.setPosY(yanterior);
        }
        
        casillerosFichas[yanterior][xanterior]=fichaMoviendo;
        return valor;
    }
    
    public boolean comprobarsiHayJake(String colorAtacado){
        llenarCasillerosAtacados(colorAtacado);
        
        for(int i=0;i<reyes.length;i++){
            String movimiento=reyes[i].getPosY()+" "+reyes[i].getPosX();
            for(int j=0;j<casillerosAtacados.size();j++){
                if(casillerosAtacados.get(j).equals(movimiento)){
                    System.out.println("");
                    return true;
                }    
            }
        }
        return false;
    }
    
    public void llenarCasillerosAtacados(String colorAtacado){
            
        for(int i=0;i<casillerosFichas.length;i++){
            for(int j=0;j<casillerosFichas[0].length;j++){
                if(casillerosFichas[i][j]!=null && !casillerosFichas[i][j].getColor().equals(colorAtacado)){
                    casillerosFichas[i][j].movimientosPosibles(casillerosAtacados, casillerosFichas, YultimoMovido, XultimoMovido);
                }
            }
        }
    }
    
    public boolean comprobarVidaReyes(){
        if(reyes[0].getVive() && reyes[1].getVive())
            return true;
        else
            return false;
    }
    public void mostrarGanador(){
        if(!reyes[0].getVive()){
            ganadortxt.setText("Gano \nel negro");
        }else{
            ganadortxt.setText("Gano \nel blanco");
        }
    
    }
    
    public void cambiarTurnoJugador(){
        
        if(turnoJugador==1){
            player1.setBackground(new Color(123,123,123));
            player2.setBackground(new Color(0,179,0));
            colorTurnoJugador="negro";
            turnoJugador=2;
            
        }else{
            player1.setBackground(new Color(0,179,0));
            player2.setBackground(new Color(123,123,123));
            turnoJugador=1;
            colorTurnoJugador="blanco";
        }
            
    }        
    
    public void colocarPieza(Ficha fich){
        String direccion;
        JButton btn=fich.getBoton();
        direccion=fich.getDireccionImagen();
        
        
        btn.setIcon(setIcono(direccion,btn));
    }
    public Icon setIcono(String url,JButton boton){
        ImageIcon icon=new ImageIcon(getClass().getResource(url));
        int ancho=boton.getWidth();   
        int alto=boton.getHeight(); 
        
        ImageIcon icono=new ImageIcon(icon.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT));
        
        return icono;
    }
    
    
    public void ponerFichasEnTableroFichas(){
        Rey rei;
        
        //fichas blancas
        casillerosFichas[6][0]= new Peon("blanco","/imagenes/peon-blanco.png",B1);
        casillerosFichas[6][1]= new Peon("blanco","/imagenes/peon-blanco.png",B2);
        casillerosFichas[6][2]= new Peon("blanco","/imagenes/peon-blanco.png",B3);
        casillerosFichas[6][3]= new Peon("blanco","/imagenes/peon-blanco.png",B4);
        casillerosFichas[6][4]= new Peon("blanco","/imagenes/peon-blanco.png",B5);
        casillerosFichas[6][5]= new Peon("blanco","/imagenes/peon-blanco.png",B6);
        casillerosFichas[6][6]= new Peon("blanco","/imagenes/peon-blanco.png",B7);
        casillerosFichas[6][7]= new Peon("blanco","/imagenes/peon-blanco.png",B8);
        casillerosFichas[7][0]= new Torre("blanco","/imagenes/torre-blanco.png",A1);
        casillerosFichas[7][7]= new Torre("blanco","/imagenes/torre-blanco.png",A8);
        casillerosFichas[7][1]= new Caballo("blanco","/imagenes/caballo-blanco.png",A2);
        casillerosFichas[7][6]= new Caballo("blanco","/imagenes/caballo-blanco.png",A7);
        casillerosFichas[7][2]= new Alfil("blanco","/imagenes/alfil-blanco.png",A3);
        casillerosFichas[7][5]= new Alfil("blanco","/imagenes/alfil-blanco.png",A6);
        casillerosFichas[7][3]= new Reina("blanco","/imagenes/reina-blanco.png",A4);
        rei=new Rey("blanco","/imagenes/rey-blanco.png",A5);
        casillerosFichas[7][4]= rei;
        reyes[0]=rei;
        //fichas negras
        casillerosFichas[1][0]= new Peon("negro","/imagenes/peon-negro.png",G1);
        casillerosFichas[1][1]= new Peon("negro","/imagenes/peon-negro.png",G2);
        casillerosFichas[1][2]= new Peon("negro","/imagenes/peon-negro.png",G3);
        casillerosFichas[1][3]= new Peon("negro","/imagenes/peon-negro.png",G4);
        casillerosFichas[1][4]= new Peon("negro","/imagenes/peon-negro.png",G5);
        casillerosFichas[1][5]= new Peon("negro","/imagenes/peon-negro.png",G6);
        casillerosFichas[1][6]= new Peon("negro","/imagenes/peon-negro.png",G7);
        casillerosFichas[1][7]= new Peon("negro","/imagenes/peon-negro.png",G8);
        casillerosFichas[0][0]= new Torre("negro","/imagenes/torre-negro.png",H1);
        casillerosFichas[0][7]= new Torre("negro","/imagenes/torre-negro.png",H8);
        casillerosFichas[0][1]= new Caballo("negro","/imagenes/caballo-negro.png",H2);
        casillerosFichas[0][6]= new Caballo("negro","/imagenes/caballo-negro.png",H7);
        casillerosFichas[0][2]= new Alfil("negro","/imagenes/alfil-negro.png",H3);
        casillerosFichas[0][5]= new Alfil("negro","/imagenes/alfil-negro.png",H6);
        casillerosFichas[0][3]= new Reina("negro","/imagenes/reina-negro.png",H4);
        rei=new Rey("negro","/imagenes/rey-negro.png",H5);
        casillerosFichas[0][4]= rei;
        reyes[1]=rei;
    }   
    
    public void ponerFichasEnBotones(){

        for(int i=0;i<casillerosFichas.length;i++){
            for(int j=0;j<casillerosFichas[0].length;j++){
                if(casillerosFichas[i][j]!=null){
                    colocarPieza(casillerosFichas[i][j]);
                }
            }
        }
        
    }
    public void llenarCasillerosBotones(){
        casillerosBotones[0][0]=H1;
        casillerosBotones[0][1]=H2;
        casillerosBotones[0][2]=H3;
        casillerosBotones[0][3]=H4;
        casillerosBotones[0][4]=H5;
        casillerosBotones[0][5]=H6;
        casillerosBotones[0][6]=H7;
        casillerosBotones[0][7]=H8;
        casillerosBotones[1][0]=G1;
        casillerosBotones[1][1]=G2;
        casillerosBotones[1][2]=G3;
        casillerosBotones[1][3]=G4;
        casillerosBotones[1][4]=G5;
        casillerosBotones[1][5]=G6;
        casillerosBotones[1][6]=G7;
        casillerosBotones[1][7]=G8;
        casillerosBotones[2][0]=F1;
        casillerosBotones[2][1]=F2;
        casillerosBotones[2][2]=F3;
        casillerosBotones[2][3]=F4;
        casillerosBotones[2][4]=F5;
        casillerosBotones[2][5]=F6;
        casillerosBotones[2][6]=F7;
        casillerosBotones[2][7]=F8;
        casillerosBotones[3][0]=E1;
        casillerosBotones[3][1]=E2;
        casillerosBotones[3][2]=E3;
        casillerosBotones[3][3]=E4;
        casillerosBotones[3][4]=E5;
        casillerosBotones[3][5]=E6;
        casillerosBotones[3][6]=E7;
        casillerosBotones[3][7]=E8;
        casillerosBotones[4][0]=D1;
        casillerosBotones[4][1]=D2;
        casillerosBotones[4][2]=D3;
        casillerosBotones[4][3]=D4;
        casillerosBotones[4][4]=D5;
        casillerosBotones[4][5]=D6;
        casillerosBotones[4][6]=D7;
        casillerosBotones[4][7]=D8;
        casillerosBotones[5][0]=C1;
        casillerosBotones[5][1]=C2;
        casillerosBotones[5][2]=C3;
        casillerosBotones[5][3]=C4;
        casillerosBotones[5][4]=C5;
        casillerosBotones[5][5]=C6;
        casillerosBotones[5][6]=C7;
        casillerosBotones[5][7]=C8;
        casillerosBotones[6][0]=B1;
        casillerosBotones[6][1]=B2;
        casillerosBotones[6][2]=B3;
        casillerosBotones[6][3]=B4;
        casillerosBotones[6][4]=B5;
        casillerosBotones[6][5]=B6;
        casillerosBotones[6][6]=B7;
        casillerosBotones[6][7]=B8;
        casillerosBotones[7][0]=A1;
        casillerosBotones[7][1]=A2;
        casillerosBotones[7][2]=A3;
        casillerosBotones[7][3]=A4;
        casillerosBotones[7][4]=A5;
        casillerosBotones[7][5]=A6;
        casillerosBotones[7][6]=A7;
        casillerosBotones[7][7]=A8;   
    }
    
    public void darCoordenadasBotones(){
        for(int i=0;i<casillerosBotones.length;i++){
            for(int j=0;j<casillerosBotones[0].length;j++){
                casillerosBotones[i][j].setAlignmentY(i/10f);
                casillerosBotones[i][j].setAlignmentX(j/10f);
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JButton D1;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton D5;
    private javax.swing.JButton D6;
    private javax.swing.JButton D7;
    private javax.swing.JButton D8;
    private javax.swing.JButton E1;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton E5;
    private javax.swing.JButton E6;
    private javax.swing.JButton E7;
    private javax.swing.JButton E8;
    private javax.swing.JButton F1;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JButton F8;
    private javax.swing.JButton G1;
    private javax.swing.JButton G2;
    private javax.swing.JButton G3;
    private javax.swing.JButton G4;
    private javax.swing.JButton G5;
    private javax.swing.JButton G6;
    private javax.swing.JButton G7;
    private javax.swing.JButton G8;
    private javax.swing.JButton H1;
    private javax.swing.JButton H2;
    private javax.swing.JButton H3;
    private javax.swing.JButton H4;
    private javax.swing.JButton H5;
    private javax.swing.JButton H6;
    private javax.swing.JButton H7;
    private javax.swing.JButton H8;
    private javax.swing.JButton btnVolverAJugar;
    private javax.swing.JPanel escogerFicha;
    private javax.swing.JLabel ganadortxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jaketxt1;
    private javax.swing.JComboBox<String> opciones;
    private javax.swing.JPanel player1;
    private javax.swing.JPanel player2;
    // End of variables declaration                   
}
